const coursesCardsData = [
  // ХУДОЖЕСТВЕННАЯ
  {
    image: {
      src: "img/Courses/35.jpg",
    },
    title: "Изостудия «Творец»",
    vacantPlaces: true,
    extraText: [5],
    category: "Художественная",
    programms: [
      {
        programmName: "Изостудия «Творец»",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Дубровская Наталия Вадимовна"],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Творческие занятия в студии – особый вид художественной деятельности, объединяющий в себе различные виды творчества: рисование, лепку, аппликацию, коллаж, витраж, конструирование.",
          "В программе: игровые занятия с изобразительными материалами; выполнение сюжетных композиций, сочетающие разные виды деятельности: рисование и конструирование, лепку и аппликацию, витраж и роспись. ",
          "Результат: в процессе творческих занятий дети смогут узнать о необычных приемах и способах в работе с изобразительными материалами - бумагой, пластиком, деревом, тканью, стеклом. Творческие работы могут служить не только украшением интерьера, но и отличным подарком к праздникам.",
        ],
        groups: [
          {
            id: 0,
            vacantPlaces:
              "Группа укомплектована (мест нет, возможна запись в резерв)",
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:30 – 17:40",
              tuesday: "",
              wednesday: "",
              thursday: "16:30 – 17:40",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 1,
            // vacantPlaces:
            //   "Группа укомплектована (мест нет, возможна запись в резерв)",
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "5 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "17:50 – 19:20",
              thursday: "",
              friday: "17:50 – 19:20",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/92616/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/34.jpg",
    },
    title: "Народная игрушка «Чудеса из сундучка»",
    extraText: [5, 6],
    category: "Художественная",
    programms: [
      {
        programmName: "Народная игрушка «Чудеса из сундучка»",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Дубровская Наталия Вадимовна"],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Народная самодельная игрушка – это прекрасная возможность познакомить детей с традициями и обычаями прошлого, на основе которых поддерживается связь поколений. ",
          "В программе: занятия проходят в форме мастер-класса, где педагог одновременно показывает технику изготовления игрушки и сопровождает комментариями об истории, назначении и ее роли в повседневной жизни.",
          "Результат: дети узнают о приемах изготовления традиционных, народных игрушек. В процессе занятий дети научаться создавать куклы-обереги, куклы к праздникам, авторские игрушки по мотивам народных сказок, украшения «в народном стиле».",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "17:50 – 19:00",
              tuesday: "",
              wednesday: "",
              thursday: "17:50 – 19:00",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/92617/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/33.jpg",
    },
    title: "Куклотерапия «Играйте, на здоровье!»",
    extraText: [5, 6],
    category: "Художественная",
    programms: [
      {
        programmName: "Куклотерапия «Играйте, на здоровье!»",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Дубровская Наталия Вадимовна"],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Куклотерапия – одно из современных направлений арт-педагогики, которое использует самодельные куклы, как способ самовыражения и исследования эмоций. Для занятий с детьми это способ игрового взаимодействия и самовыражения, помогающий развивать фантазию, воображение и пространственное мышление.",
          "В программе: дети научаться придумывать и создавать игровые куклы / пальчиковые, куклы-марионетки, мягкие игрушки, интерьерные куклы.",
          "Результат: благодаря куклотерапии в группе создается особая творческая атмосфера, которая способствует развитию личности ребенка: формирование нравственно-этических навыков, развитие речи, мелкой моторики, быстрое решение проблемных ситуаций.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "19:10 – 19:40",
              tuesday: "",
              wednesday: "",
              thursday: "19:10 – 19:40",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/92618/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/5.jpg",
    },
    title: "Творческая студия «Цвет»",
    extraText: [5, 6, 7, 8],
    category: "Художественная",
    programms: [
      {
        programmName: "Творческая студия «Цвет»",
        teacher: {
          teacherPic: ["./img/About/18.png"],
          teacherName: ["Мершеева Евгения Александровна"],
        },
        category: "художественная",
        duration: "2 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Программа ориентирована на развитие индивидуальных способностей ребёнка, самореализации личности через формирование интереса к декоративно-прикладному творчеству и изобразительному искусству. Благодаря занятиям у детей проявляется наблюдательность, формируются сенсорные способности: глазомер, зрительная оценка пропорции, чувство цвета, ритма, необходимые для выразительного творческого решения изобразительных задач, развития художественно-творческих способностей.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "17:20 – 18:30",
              wednesday: "",
              thursday: "17:20 – 18:30",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "6-7 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "18:10 – 19:30",
              tuesday: "",
              wednesday: "18:10 – 19:30",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа № 3",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "15:00 – 16:40",
              wednesday: "",
              thursday: "15:00 – 16:40",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton:
          "https://dopobr.petersburgedu.ru/programs/90502/?save_filters=%3Fordering%3D-updated_at%26search%3D%25D0%25A6%25D0%25B2%25D0%25B5%25D1%2582",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/1.jpg",
    },
    title: "Вокальный ансамбль «Маленькие звездочки»",
    extraText: [5, 6, 7, 8, 9, 10],
    category: "Художественная",
    programms: [
      {
        programmName:
          "Вокальный ансамбль «Маленькие звездочки» (первые шаги в музыке)",
        teacher: {
          teacherPic: ["./img/About/11.png"],
          teacherName: ["Гольцова Наталья Георгиевна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "В процессе изучения вокала (в том числе эстрадного) дети осваивают основы вокального исполнительства, развивают художественный вкус, расширяют кругозор, познают основы актерского мастерства. Именно для того, чтобы ребенок, наделенный способностью и тягой к творчеству, развитию своих вокальных способностей, мог овладеть умениями и навыками вокального искусства, самореализоваться в творчестве, научиться голосом передав",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "17:05 – 17:35",
              friday: "",
              saturday: "13:05 – 13:35",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "2-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "17:45 – 18:15",
              friday: "",
              saturday: "13:45 – 14:15",
            },
          },
          {
            id: 2,
            groupName: "Группа № 3",
            year: "3-й год обучения",
            age: "7 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "14:30 – 16:00",
              friday: "",
              saturday: "10:30 – 12:00",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5325/groups/",
      },
      {
        programmName: "Вокальный ансамбль «Маленькие звездочки»",
        teacher: {
          teacherPic: ["./img/About/11.png"],
          teacherName: ["Гольцова Наталья Георгиевна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "С раннего возраста дети чувствуют потребность в эмоциональном общении, испытывают тягу к творчеству. Именно в период детства важно реализовать творческий потенциал ребенка, сформировать певческие навыки, приобщить детей к певческому искусству, которое способствует развитию творческой фантазии. Каждый ребенок находит возможность для творческого самовыражения личности через сольное и ансамблевое пение, пение народных и современных песен с музыкальным сопровождением.",
        ],
        groups: [
          {
            id: 3,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "6-7 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "15:00 – 15:45",
              tuesday: "",
              wednesday: "15:00 – 15:45",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 4,
            groupName: "Группа № 2",
            year: "2-й год обучения",
            age: "8-9 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "16:10 – 16:55",
              friday: "",
              saturday: "12:10 – 12:55",
            },
          },
          {
            id: 5,
            groupName: "Группа № 3",
            year: "3-й год обучения",
            age: "9-10 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:00 – 17:40",
              tuesday: "",
              wednesday: "16:00 – 17:40",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5324/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/39.jpg",
    },
    title: "Керамисты",
    extraText: [5, 6, 7, 8, 9, 10, 11, 12],
    vacantPlaces: true,
    // extraInfo: [
    //   {
    //     text: "Укомплектовано",
    //     description: "Мест нет - возможна запись в резерв",
    //   },
    // ],
    category: "Художественная",
    programms: [
      {
        programmName: "Керамисты",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Сабирова Динара Рафаиловна"],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Программа поможет понять процесс производства керамических изделий, как декоративных, так и полезных в быту. Ознакомятся с разными техниками работы с глиной,  декорирования и росписи",
        ],
        groups: [
          {
            id: 0,
            // vacantPlaces:
            //   "Группа укомплектована (мест нет, возможна запись в резерв)",
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "17:20 – 18:30",
              saturday: "",
            },
          },
          {
            id: 1,
            // vacantPlaces:
            //   "Группа укомплектована (мест нет, возможна запись в резерв)",
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:50 – 18:30",
              tuesday: "",
              wednesday: "16:50 – 18:30",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            // vacantPlaces:
            //   "Группа укомплектована (мест нет, возможна запись в резерв)",
            groupName: "Группа № 3",
            year: "1-й год обучения",
            age: "9-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "18:40 – 20:20",
              thursday: "",
              friday: "18:40 – 20:20",
              saturday: "",
            },
          },
          {
            id: 3,
            // vacantPlaces:
            //   "Группа укомплектована (мест нет, возможна запись в резерв)",
            groupName: "Группа № 4",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "15:00 – 16:40",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "15:00 – 16:40",
              saturday: "",
            },
          },
          {
            id: 4,
            // vacantPlaces:
            //   "Группа укомплектована (мест нет, возможна запись в резерв)",
            groupName: "Группа № 5",
            year: "1-й год обучения",
            age: "9-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "18:40 – 20:20",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "16:00 – 17:40",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/97009/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/15.jpg",
    },
    title: "Коллектив современного и эстрадного танца «Magic Dance»",
    extraText: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    category: "Художественная",
    programms: [
      {
        programmName: "Коллектив современного и эстрадного танца «Magic Dance»",
        teacher: {
          teacherPic: [
            "./img/About/women-avatar.png",
            "./img/About/16.png",
            "./img/About/22.png",
            "./img/About/women-avatar.png",
          ],
          teacherName: [
            "Орлова Ирина Павловна",
            "Логунова Наталья Александровна",
            "Самокрайняя Александра Сергеевна",
            "Ибрагимова София Фенисовна",
          ],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Коллектив современного и эстрадного танца «Magic Dance» направлен на всестороннее развитие общих физических и художественных навыков.",
          "В коллективе обучающиеся получат навыки классической хореографии, изучат современные и эстрадное направления.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            extraGroupName: "Дошкольники",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "12:20 – 13:10",
              wednesday: "",
              thursday: "",
              friday: "17:40 – 18:40",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            extraGroupName: "Magic Baby",
            year: "1-й год обучения",
            age: "6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "18:10 – 19:10",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа № 3",
            extraGroupName: "Mix-Dance (младшая)",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "14:10 – 15:40",
              wednesday: "",
              thursday: "14:10 – 15:40",
              friday: "14:10 – 15:40",
              saturday: "14:00 – 15:30",
            },
          },
          {
            id: 3,
            groupName: "Группа № 4",
            extraGroupName: "2-3 класс",
            year: "1-й год обучения",
            age: "8-9 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "14:20 – 15:50",
              wednesday: "14:20 – 15:50",
              thursday: "",
              friday: "14:20 – 15:50",
              saturday: "12:20 – 13:50",
            },
          },
          {
            id: 4,
            groupName: "Группа № 5",
            extraGroupName: "Mix-Dance (средняя)",
            year: "1-й год обучения",
            age: "10-11 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "14:20 – 15:50",
              wednesday: "14:20 – 15:50",
              thursday: "",
              friday: "14:10 – 15:40",
              saturday: "12:20 – 13:50",
            },
          },
          {
            id: 5,
            groupName: "Группа № 6",
            extraGroupName: "Старт",
            year: "1-й год обучения",
            age: "10-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "16:00 – 17:30",
              wednesday: "",
              thursday: "",
              friday: "16:00 – 17:30",
              saturday: "14:00 – 15:30",
            },
          },
          {
            id: 6,
            groupName: "Группа № 7",
            extraGroupName: "Старт-Dance",
            year: "1-й год обучения",
            age: "12-15 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "16:00 – 17:30",
              thursday: "16:30 – 18:00",
              friday: "16:00 – 17:30",
              saturday: "15:40 – 17:10",
            },
          },
          {
            id: 7,
            groupName: "Группа № 8",
            extraGroupName: "Младший ансамбль",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "17:40 – 19:10",
              wednesday: "",
              thursday: "",
              friday: "17:40 – 19:10",
              saturday: "14:00 – 15:30",
            },
          },
          {
            id: 8,
            groupName: "Группа № 9",
            extraGroupName: "Средний ансамбль",
            year: "1-й год обучения",
            age: "10-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "17:40 – 19:10",
              wednesday: "",
              thursday: "",
              friday: "17:40 – 19:10",
              saturday: "15:40 – 17:10",
            },
          },
          {
            id: 9,
            groupName: "Группа № 10",
            extraGroupName: "Старший ансамбль",
            year: "1-й год обучения",
            age: "12-15 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "16:00 – 17:30",
              wednesday: "17:40 – 19:10",
              thursday: "16:30 – 18:00",
              friday: "",
              saturday: "17:20 – 19:00",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/70092/groups/",
      },
    ],
    achievements: [
      "./img/Courses/Achievements/15-1.jpeg",
      "./img/Courses/Achievements/15-2.jpeg",
      "./img/Courses/Achievements/15-3.jpeg",
      "./img/Courses/Achievements/15-4.jpeg",
      "./img/Courses/Achievements/15-5.jpeg",
      "./img/Courses/Achievements/15-6.jpeg",
      "./img/Courses/Achievements/15-7.jpg",
      "./img/Courses/Achievements/15-8.jpeg",
    ],
  },
  {
    image: {
      src: "img/Courses/16.jpg",
    },
    title: "Гончарная мастерская",
    extraText: [6, 7, 8, 9, 10, 11, 12, 13, 15],
    category: "Художественная",
    programms: [
      {
        programmName: "Гончарная мастерская",
        teacher: {
          teacherPic: ["./img/About/21.png"],
          teacherName: ["Рябченко-Лякс Наталья Сергеевна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Данная программа направлена на освоение навыков гончарного искусства. На занятиях обучающиеся смогут создавать свои изделия из глины с последующим обжигом и росписью.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "7-9 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "16:00 – 17:40",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "2-й год обучения",
            age: "10-15 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "16:00 – 17:40",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа № 3",
            year: "1-й год обучения",
            age: "6-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "17:50 – 19:30",
              wednesday: "",
              thursday: "17:50 – 19:30",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/70097/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/12.jpg",
    },
    title: "Золотой наперсток",
    extraText: [6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17],
    category: "Художественная",
    programms: [
      {
        programmName: "Золотой наперсток",
        teacher: {
          teacherPic: ["./img/About/23.png"],
          teacherName: ["Степаненко Лилия Викторовна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Данная программа поможет обучающимся научиться работать с выкройками и разрабатывать свои собственные эскизы, освоить швейное дело, ковровую вышивку. По итогу обучающиеся изготовят свою собственную линию одежды.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "6-7 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "19:00 – 20:40",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "13:00 – 14:00",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "15:00 – 16:40",
              wednesday: "",
              thursday: "15:00 – 16:40",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа № 3",
            year: "2-й год обучения",
            age: "9-11 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "16:50 – 18:30",
              wednesday: "",
              thursday: "16:50 – 18:30",
              friday: "",
              saturday: "16:40 – 18:20",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/70064/groups/",
      },
      {
        programmName: "Золотой наперсток. Дизайн одежды",
        teacher: {
          teacherPic: ["./img/About/23.png"],
          teacherName: ["Степаненко Лилия Викторовна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Данная программа поможет обучающимся научиться работать с выкройками и разрабатывать свои собственные эскизы, освоить швейное дело, ковровую вышивку. По итогу обучающиеся изготовят свою собственную линию одежды.",
        ],
        groups: [
          {
            id: 3,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "15-17 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "19:00 – 20:40",
              friday: "",
              saturday: "14:30 – 16:10",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/90301/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/36.jpg",
    },
    title: "Живопись",
    extraText: [7, 8],
    category: "Художественная",
    programms: [
      {
        programmName: "Живопись",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Дубровская Наталия Вадимовна"],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Живопись – вид изобразительного искусства для передачи эмоционального состояния красками.  Основное средство изображения – цвет. ",
          "В программе: создание живописных композиций красками: акварель, гуашь, а также с использованием нетрадиционных материалов пластилин, шерсть, тушь.",
          "Результат: в процессе творческих занятий дети освоят основные техники в работе с гуашью и акварелью, научатся воплощать на бумаге свои идеи и фантазии. С помощью художественных приемов дети откроют секреты в жанре пейзажа, портрета и натюрморта.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "16:10 – 17:40",
              thursday: "",
              friday: "16:10 – 17:40",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/92619/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/13.jpg",
    },
    title: "Студия вязания",
    extraText: [7, 8, 9, 10, 11, 12],
    category: "Художественная",
    programms: [
      {
        programmName: "Студия вязания «Паутинка»",
        teacher: {
          teacherPic: ["./img/About/15.png"],
          teacherName: ["Ларина Наталья Владимировна"],
        },
        category: "художественная",
        duration: "2 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Обучающиеся овладеют базовыми навыками вязания крючком. В ходе программы научаться создавать различные сувениры, аксессуары и игрушки.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "7-9 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "15:00 – 16:40",
              tuesday: "",
              wednesday: "15:00 – 16:40",
              thursday: "",
              friday: "15:00 – 16:40",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/70065/groups/",
      },
      {
        programmName: "Студия вязания «Чудесный клубок»",
        teacher: {
          teacherPic: ["./img/About/15.png"],
          teacherName: ["Ларина Наталья Владимировна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "В ходе данной программы обучающиеся освоят базовые навыки вязания спицами. Смогут создать теплые вещи для себя и друзей. Создадут модные аксессуары: сумки, чехлы, одежду для животных.",
        ],
        groups: [
          {
            id: 1,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "9-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:50 – 18:30",
              tuesday: "",
              wednesday: "16:50 – 18:30",
              thursday: "",
              friday: "16:50 – 18:30",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/70066/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/2.jpg",
    },
    title: "Академия рукоделия",
    extraText: [7, 8, 9, 10, 11, 12, 13, 14, 15],
    category: "Художественная",
    programms: [
      {
        programmName: "Академия рукоделия. Стильные аксессуары и украшения",
        teacher: {
          teacherPic: ["./img/About/12.png"],
          teacherName: ["Дерец Юлиана Валентиновна"],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Благодаря данной программе дети научатся делать современные уникальные украшения и аксессуары ручной работы: заколки, броши, бусы и многое другое из разнообразных материалов (ткани, бусин, шерсти, фетра и др.)",
          "Использование сочетания различных техник декоративно-прикладной деятельности позволяет обучающимся:",
          "- посещая одно объединение, попробовать заняться разными видами творчества;",
          "- овладеть доступными навыками и техниками в различных направлениях творческой деятельности;",
          "- приобщиться к миру декоративно-прикладного искусства;",
          "- создавать полезные и красивые изделия для себя и своих близких.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "7-9 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "14:30 – 16:10",
              wednesday: "",
              thursday: "14:30 – 16:10",
              friday: "",
              saturday: "14:30 – 16:10",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/90296/groups/",
      },
      {
        programmName: "Академия рукоделия. Валяние из шерсти",
        teacher: {
          teacherPic: ["./img/About/12.png"],
          teacherName: ["Дерец Юлиана Валентиновна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "В ходе освоения программы дети приобщаются к декоративно-прикладному искусству, познают культуру своей и других стран, приобретают практические навыки декоративно-прикладного творчества. Овладение ремеслом валяния вызывает интерес у учащихся, так как шерстяные вещи и игрушки – красивые, модные, теплые, легки в изготовлении, разнообразны по назначению.",
        ],
        groups: [
          {
            id: 1,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "10-15 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "16:20 – 18:00",
              wednesday: "",
              thursday: "16:20 – 18:00",
              friday: "",
              saturday: "16:20 – 18:00",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5327/groups/",
      },
      {
        programmName: "Академия рукоделия. Мягкая Игрушка",
        teacher: {
          teacherPic: ["./img/About/12.png"],
          teacherName: ["Дерец Юлиана Валентиновна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "В ходе освоения программы дети приобщаются к декоративно-прикладному искусству, познают культуру своей и других стран, приобретают практические навыки декоративно-прикладного творчества. Игрушка, сделанная своими руками, выполненная в различных техниках и из различных материалов, помогает детям развивать диалектическое мышление, способность соединять то, что кажется не соединимым. Процесс создания игрушки помогает ребенку развить воображение, фантазию и талант. В результате, игрушка, сделанная своими руками, ценностна и значима для детей и взрослых.",
        ],
        groups: [
          {
            id: 2,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "10-15 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "18:30 – 20:10",
              wednesday: "",
              thursday: "18:30 – 20:10",
              friday: "",
              saturday: "18:30 – 20:10",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/36099/groups/",
      },
    ],
    achievements: [
      "./img/Courses/Achievements/2-1.jpg",
      "./img/Courses/Achievements/2-2.jpg",
      "./img/Courses/Achievements/2-3.jpg",
      "./img/Courses/Achievements/2-4.jpg",
    ],
  },
  {
    image: {
      src: "img/Courses/17.jpg",
    },
    title: "Мастерская художника",
    extraText: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    category: "Художественная",
    programms: [
      {
        programmName: "Мастерская художника",
        teacher: {
          teacherPic: ["./img/About/21.png"],
          teacherName: ["Рябченко-Лякс Наталья Сергеевна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Комплексная программа, направленная на изучения изобразительного искусства начиная с самых основ.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "11-15 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "17:50 – 19:30",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "17:50 – 19:30",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "7-10 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:00 – 17:40",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "16:00 – 17:40",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа № 3",
            extraGroupName: "Для детей с ОВЗ",
            year: "1-й год обучения",
            age: "7-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "15:00 – 16:10",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 3,
            groupName: "Группа № 4",
            extraGroupName: "Для детей с ОВЗ (ДДИ №3)",
            year: "1-й год обучения",
            age: "7-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "16:30 – 17:30",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/70098/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/Summer/14.jpg",
    },
    title: "Театральная студия «Сказка»",
    extraText: [10, 11, 12],
    category: "Художественная",
    programms: [
      {
        programmName: `Театральная студия «Сказка»`,
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Налимова Мария Анатольевна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Ребят ждут:",
          "- увлекательные и интересные занятия по актерскому мастерству, на которых они познакомятся с актерскими играми и этюдами;",
          "- упражнения с мячом и сценическое движение;",
          "- занятия сценической речью, помогающие четко и правильно говорить, развивающие память;",
          "- знакомство с искусством грима, различными видами костюмов",
          "Так же ребята узнают, что такое декорации и реквизит. Занятия проходят весело и интересно. Мы ставим различные спектакли, юмористические сценки и веселые клоунские номера",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "10-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "17:00 – 19:30",
              wednesday: "",
              thursday: "17:00 – 19:30",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/91326/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/20.jpg",
    },
    title: "Художественная мастерская «Исследователи»",
    extraText: [10, 11, 12, 13, 14],
    category: "Художественная",
    programms: [
      {
        programmName: `Художественная мастерская «Исследователи»`,
        teacher: {
          teacherPic: ["./img/About/18.png"],
          teacherName: ["Мершеева Евгения Александровна"],
        },
        category: "художественная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Программа ориентирована на реализацию проектной деятельности, в ходе которой обучающиеся детально изучат виды изобразительного искусства и декоративно-прикладного творчества, через создание авторских копий и оформление проектов, а также презентации своих творческих работ.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "10-14 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:00 – 17:40",
              tuesday: "",
              wednesday: "16:00 – 17:40",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton:
          "https://dopobr.petersburgedu.ru/programs/90503/?save_filters=%3Fordering%3D-updated_at%26search%3D%25D0%259C%25D0%25B0%25D1%2581%25D1%2582%25D0%25B5%25D1%2580%25D1%2581%25D0%25BA%25D0%25B0%25D1%258F",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/14.jpg",
    },
    title: "Студия вышивки",
    extraText: [14, 15, 16, 17],
    category: "Художественная",
    programms: [
      {
        programmName: "Студия вышивки «Искусница»",
        teacher: {
          teacherPic: ["./img/About/15.png"],
          teacherName: ["Ларина Наталья Владимировна"],
        },
        category: "художественная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "В ходе данной программы обучающиеся смогут ознакомиться с разными техниками вышивки по трикотажу и декорирования одежды.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "14-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "19:00 – 20:30",
              tuesday: "",
              wednesday: "19:00 – 20:30",
              thursday: "",
              friday: "19:00 – 20:30",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/70068/groups/",
      },
    ],
  },
  // ТЕХНИЧЕСКАЯ
  {
    image: {
      src: "img/Courses/8.jpg",
    },
    title: "Дизайн-студия «Впечатление»",
    extraText: [6, 7, 8, 9, 10, 11, 12, 13],
    category: "Техническая",
    programms: [
      {
        programmName: "Дизайн-студия «Впечатление»",
        teacher: {
          teacherPic: ["./img/About/24.png"],
          teacherName: ["Ярош Лариса Николаевна"],
        },
        category: "техническая",
        duration: "2 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Занятия по художественному конструированию способствуют более гармоничному развитию ребенка, так как формируют пространственное мышление (проектную культуру), необходимое для будущей творческой деятельности в любой профессиональной области. Конструирование из бумаги – это именно тот вид деятельности художника, который в полном объеме дает все знания и навыки, изобретенные в ходе развития истории искусства.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "6-7 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "17:20 – 19:00",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "12:50 – 14:30",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "15:30 – 17:10",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "11:00 – 12:40",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5359/groups/",
      },
      {
        programmName: "Дизайн-студия «Впечатление» PRO",
        teacher: {
          teacherPic: ["./img/About/24.png"],
          teacherName: ["Ярош Лариса Николаевна"],
        },
        category: "техническая",
        duration: "2 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Занятия по художественному конструированию способствуют более гармоничному развитию ребенка, так как формируют пространственное мышление (проектную культуру), необходимое для будущей творческой деятельности в любой профессиональной области. Конструирование из бумаги – это именно тот вид деятельности художника, который в полном объеме дает все знания и навыки, изобретенные в ходе развития истории искусства.",
        ],
        groups: [
          {
            id: 2,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "11-13 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "17:20 – 19:00",
              wednesday: "",
              thursday: "",
              friday: "17:20 – 19:00",
              saturday: "",
            },
          },
          {
            id: 3,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "10-11 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "15:30 – 17:10",
              wednesday: "",
              thursday: "",
              friday: "15:30 – 17:10",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/18929/groups/",
      },
    ],
    achievements: ["./img/Courses/Achievements/8-1.jpg"],
  },
  {
    image: {
      src: "img/Courses/40.jpg",
    },
    title: "Технология",
    vacantPlaces: true,
    extraText: [10, 11, 12, 13, 14],
    category: "Техническая",
    programms: [
      {
        programmName: "Технология",
        teacher: {
          teacherPic: ["./img/About/men-avatar.png"],
          teacherName: ["Михаевич Вадим Константинович"],
        },
        category: "техническая",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: ["Научись пилить, строгать, выжигать!"],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "10-14 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "17:00 – 19:30",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/97934/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/9.jpg",
    },
    title: "Анимация в 2D и 3D пространстве",
    vacantPlaces: false,
    extraText: [10, 11, 12, 13, 14, 15, 16, 17],
    category: "Техническая",
    programms: [
      {
        programmName: "Анимация в 2D и 3D пространстве",
        teacher: {
          teacherPic: ["./img/About/men-avatar.png"],
          teacherName: ["Жамалов Тимур Рамильевич"],
        },
        category: "техническая",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Приглашаем всех желающих в увлекательное объединение «Анимация в 2D и 3D пространстве»! Вас ждут захватывающие уроки по созданию мультфильмов.",
          "Мы научимся работать с программным обеспечением для анимации (Blender), создавать персонажей, оживлять их движения и разрабатывать уникальные сюжеты. Занятия станут отличным стартом для тех, кто мечтает о карьере в сфере анимации и дизайна!",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "10-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "17:50 – 19:30",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "10-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "12:50 – 14:30",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/97934/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/41.jpg",
    },
    title: "VR-программирование и 3D моделирование",
    vacantPlaces: true,
    extraText: [12, 13, 14, 15, 16, 17],
    category: "Техническая",
    programms: [
      {
        programmName: "VR-программирование и 3D моделирование",
        teacher: {
          teacherPic: ["./img/About/men-avatar.png"],
          teacherName: ["Жамалов Тимур Рамильевич"],
        },
        category: "техническая",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Интересуетесь виртуальной реальностью, но не знаете, с чего начать? Добро пожаловать в «VR-программирование и 3D моделирование»! Мы поможем вам сделать первые шаги в мире разработки VR-приложений и познакомим вас с основными инструментами и техниками 3D-моделирования.",
          "Вы научитесь создавать простые формы, а затем перейдете к более сложным моделям. Далее мы изучим основы программирования, покажем, как работают VR-технологии, и вместе создадим простые, но впечатляющие проекты.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "12-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "16:00 – 17:40",
              saturday: "11:00 – 12:40",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/97934/groups/",
      },
    ],
  },
  // СОЦИАЛЬНО-ГУМАНИТАРНАЯ
  {
    image: {
      src: "img/Courses/30.jpg",
    },
    title: "Шекспирята",
    extraText: [5, 6, 7],
    category: "Социально-гуманитарная",
    programms: [
      {
        programmName: "Шекспирята",
        teacher: {
          teacherPic: ["./img/About/17.png"],
          teacherName: ["Матвеева Наталья Евгеньевна"],
        },
        category: "социально-гуманитарная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Изучение иностранных языков через литературные произведения",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "17:30 – 18:40",
              thursday: "",
              friday: "17:30 – 18:40",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "5-7 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "18:50 – 20:00",
              thursday: "",
              friday: "18:50 – 20:00",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/90329/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/6.jpg",
    },
    title: "Английский клуб",
    extraText: [5, 6, 7, 8, 9, 10, 11, 12, 13],
    category: "Социально-гуманитарная",
    programms: [
      {
        programmName: "Английский клуб для малышей",
        teacher: {
          teacherPic: ["./img/About/20.png"],
          teacherName: ["Ревенкова Екатерина Владимировна"],
        },
        category: "социально-гуманитарная",
        duration: "2 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Учащиеся в игровой форме знакомятся с обычаями и традициями другой страны и приобретают практические навыки владения иностранным языком.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "10:00 – 11:10",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5340/groups/",
      },
      {
        programmName: "Английский клуб: Юниоры, 1 ступень",
        teacher: {
          teacherPic: ["./img/About/20.png"],
          teacherName: ["Ревенкова Екатерина Владимировна"],
        },
        category: "социально-гуманитарная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Обучение по программе способствует овладению навыками продуктивной и рецептивной речевой деятельности: аудирования, говорения, чтения, письма. Учащиеся приобретают навыки, предусмотренные соответствующим уровнем, формируют коммуникативные умения в четырех видах речевой деятельности.",
        ],
        groups: [
          {
            id: 1,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "8-9 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "14:50 – 16:30",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "11:20 – 14:00",
            },
          },
          {
            id: 2,
            groupName: "Группа № 2",
            year: "3-й год обучения",
            age: "9-10 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "14:50 – 16:30",
              tuesday: "",
              wednesday: "",
              thursday: "14:50 – 16:30",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 3,
            groupName: "Группа № 3",
            year: "3-й год обучения",
            age: "9-10 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "16:40 – 18:20",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "14:30 – 16:10",
            },
          },
          {
            id: 4,
            groupName: "Группа № 4",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "18:50 – 20:30",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "16:20 – 18:40",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5342/groups/",
      },
      {
        programmName: "Английский клуб: Юниоры, 2 ступень",
        teacher: {
          teacherPic: ["./img/About/20.png"],
          teacherName: ["Ревенкова Екатерина Владимировна"],
        },
        category: "социально-гуманитарная",
        duration: "3 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Обучение по программе способствует овладению навыками продуктивной и рецептивной речевой деятельности: аудирования, говорения, чтения, письма. Учащиеся приобретают навыки, предусмотренные соответствующим уровнем, формируют коммуникативные умения в четырех видах речевой деятельности.",
        ],
        groups: [
          {
            id: 5,
            groupName: "Группа № 1",
            year: "3-й год обучения",
            age: "12-13 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "18:50 – 20:30",
              tuesday: "",
              wednesday: "",
              thursday: "18:50 – 20:30",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 6,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "10-11 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:40 – 18:20",
              tuesday: "",
              wednesday: "",
              thursday: "16:40 – 18:20",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5342/groups/",
      },
    ],
    achievements: ["./img/Courses/Achievements/6-1.jpg"],
  },
  {
    image: {
      src: "img/Courses/25.jpg",
    },
    title: "К.И.Т (для детей с ОВЗ)",
    extraText: [7, 8, 9, 10],
    category: "Социально-гуманитарная",
    programms: [
      {
        programmName: `К.И.Т (для детей с ОВЗ)`,
        teacher: {
          teacherPic: ["./img/About/18.png"],
          teacherName: ["Мершеева Евгения Александровна"],
        },
        category: "социально-гуманитарная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Программа «К.И.Т» для детей с ограниченными возможностями здоровья ориентирована на создание условий для развития творческих способностей обучающихся, повышение самооценки, и социальной интеграции через игру и творчество.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "7-10 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "15:00 – 15:45",
              tuesday: "",
              wednesday: "15:00 – 15:45",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/90504/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/37.jpg",
    },
    title: "Журналистика",
    extraText: [10, 11, 12, 13, 14, 15, 16],
    category: "Социально-гуманитарная",
    programms: [
      {
        programmName: `Журналистика`,
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Комиссарова Любовь Алексеевна"],
        },
        category: "социально-гуманитарная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "В программе: создание газеты, написание текстов, ведение блогов, монтаж видео",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1 (интернет-журналистика)",
            year: "1-й год обучения",
            age: "14-16 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "19:00 – 20:40",
              wednesday: "19:00 – 20:40",
              thursday: "",
              friday: "19:00 – 20:40",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2 (тележурналистика)",
            year: "1-й год обучения",
            age: "10-14 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "17:00 – 18:40",
              tuesday: "",
              wednesday: "17:00 – 18:40",
              thursday: "",
              friday: "17:00 – 18:40",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа № 3 (издательская деятельность)",
            year: "1-й год обучения",
            age: "10-15 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "19:00 – 20:40",
              tuesday: "17:00 – 18:40",
              wednesday: "",
              thursday: "17:00 – 18:40",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/96659/groups/",
      },
    ],
  },
  // ФИЗКУЛЬТУРНО-СПОРТИВНАЯ
  {
    image: {
      src: "img/Courses/7.jpg",
    },
    title: "Центр развития Шисоку-каратэ",
    extraText: [5, 6, 7, 8, 9, 10, 11, 12],
    category: "Физкультурно-спортивная",
    programms: [
      {
        programmName: "Центр развития Шисоку-каратэ",
        teacher: {
          teacherPic: ["./img/About/9.png"],
          teacherName: ["Баранов Евгений Сергеевич"],
        },
        category: "физкультурно-спортивная",
        duration: "5 лет",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Изучение данного стиля восточных единоборств, восточной философии, которая лежит в основе стиля, расширяет кругозор ребенка, формируя общую культуру. В процессе тренировок, построенных не только по принципу поступательного освоения материала, но и систематического повторения уже изученного, учащиеся секции учатся настойчиво трудиться и терпеливо переносить трудности, у них развивается моральная и психологическая устойчивость.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "10-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "19:10 – 20:50",
              tuesday: "",
              wednesday: "19:10 – 20:50",
              thursday: "",
              friday: "",
              saturday: "12:00 – 13:40",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "7-10 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "17:20 – 19:00",
              tuesday: "",
              wednesday: "17:20 – 19:00",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5356/groups/",
      },
      {
        programmName: "Центр развития Шисоку-каратэ для малышей",
        teacher: {
          teacherPic: ["./img/About/17.png"],
          teacherName: ["Матвеева Наталья Евгеньевна"],
        },
        category: "физкультурно-спортивная",
        duration: "2 года",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Изучение данного стиля восточных единоборств, восточной философии, которая лежит в основе стиля, расширяет кругозор ребенка, формируя общую культуру. В процессе тренировок, построенных не только по принципу поступательного освоения материала, но и систематического повторения уже изученного, учащиеся секции учатся настойчиво трудиться и терпеливо переносить трудности, у них развивается моральная и психологическая устойчивость.",
        ],
        groups: [
          {
            id: 2,
            groupName: "Группа № 1",
            year: "2-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "19:20 – 20:05",
              wednesday: "",
              thursday: "19:20 – 20:05",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 3,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "17:00 – 18:00",
              wednesday: "",
              thursday: "17:00 – 18:00",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 4,
            groupName: "Группа № 3",
            year: "1-й год обучения",
            age: "6-7 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "18:10 – 19:10",
              wednesday: "",
              thursday: "18:10 – 19:10",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/5357/groups/",
      },
    ],
    achievements: [
      "./img/Courses/Achievements/7-1.jpg",
      "./img/Courses/Achievements/7-2.jpg",
    ],
  },
  {
    image: {
      src: "img/Courses/38.jpg",
    },
    title: "Акробатика",
    extraText: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    extraInfo: ["Платно"],
    category: "Физкультурно-спортивная",
    programms: [
      {
        programmName: "Акробатика",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Копцева Елизавета Михайловна"],
        },
        category: "физкультурно-спортивная",
        duration: "1 год",
        price: "на платной основе -  4 500,0 руб. в месяц",
        description: [
          "Спортивная акробатика. Прыжковая акробатика. Танцевальная акробатика. Тренер: Копцева Елизавета Михайловна, мастер спорта по спортивной аэробике, КМС по спортивной гимнастике. Образование высшее, педагогическое. Стаж работы 16 лет.",
          "Студия аккредитована в федерации спортивной акробатики Санкт-Петербурга. Дети выступают на соревнованиях, получают спортивные разряды.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "5-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "16:00 – 17:00",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "5-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "15:10 – 15:55",
              tuesday: "",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/31.jpg",
    },
    title: "Юнармия",
    extraText: [7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17],
    category: "Физкультурно-спортивная",
    programms: [
      {
        programmName: "Юнармия",
        teacher: {
          teacherPic: ["./img/About/men-avatar.png"],
          teacherName: ["Кузнецов Алексей Юрьевич"],
        },
        category: "физкультурно-спортивная",
        duration: "1 год",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Юнармия — это уникальная возможность для молодых людей проявить себя, развить лидерские качества, научиться работать в команде и стать настоящими патриотами своей страны.",
          "Что ждёт участников:",
          "- участие в военно-спортивных играх и соревнованиях;",
          "- посещение культурных и спортивных мероприятий;",
          "- слёты и тематические смены в лагерях;",
          "- караульная служба у Вечного огня;",
          "- волонтёрская работа на главных событиях города и района;",
          "- изучение дисциплин начальной военной подготовки.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа № 1",
            year: "1-й год обучения",
            age: "7-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "19:00 – 20:40",
              wednesday: "",
              thursday: "",
              friday: "",
              saturday: "11:00 – 12:40",
            },
          },
          {
            id: 1,
            groupName: "Группа № 2",
            year: "1-й год обучения",
            age: "13-17 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "",
              thursday: "19:00 – 20:40",
              friday: "",
              saturday: "13:30 – 15:05",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/91511/groups/",
      },
    ],
  },
];

export default coursesCardsData;
