const coursesCardsData = [
  // Частично укомплектовано
  {
    image: {
      src: "img/Courses/15.jpg",
    },
    title: "Коллектив современного и эстрадного танца «Magic Dance»",
    vacantPlaces: true,
    extraText: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName:
          "Коллектив современного и эстрадного танца «Magic Dance» (Ибрагимова С.Ф.)",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Ибрагимова София Фенисовна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Коллектив современного и эстрадного танца «Magic Dance» направлен на всестороннее развитие общих физических и художественных навыков.",
          "В коллективе обучающиеся получат навыки классической хореографии, изучат современные и эстрадное направления.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 7-9 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-9 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "12:50 – 14:20",
              wednesday: "12:50 – 14:20",
              thursday: "12:50 – 14:20",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа 10-14 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "10-14 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "15:00 – 16:30",
              wednesday: "",
              thursday: "15:00 – 16:30",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            vacantPlaces: "Группа укомплектована, мест нет",
            groupName: "Группа 4-6 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "4-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "16:40 – 17:40",
              wednesday: "",
              thursday: "16:40 – 17:40",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/88875/groups/",
      },
      {
        programmName:
          "Коллектив современного и эстрадного танца «Magic Dance» (Самокрайняя А.С.)",
        teacher: {
          teacherPic: ["./img/About/22.png"],
          teacherName: ["Самокрайняя Александра Сергеевна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Коллектив современного и эстрадного танца «Magic Dance» направлен на всестороннее развитие общих физических и художественных навыков.",
          "В коллективе обучающиеся получат навыки классической хореографии, изучат современные и эстрадное направления.",
        ],
        groups: [
          {
            id: 3,
            groupName: "Группа 10-13 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "10-13 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "13:15 – 14:00",
              thursday: "",
              friday: "13:15 – 14:00",
              saturday: "",
            },
          },
          {
            id: 4,
            groupName: "Группа 10-13 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "10-13 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "14:10 – 15:40",
              thursday: "",
              friday: "14:10 – 15:40",
              saturday: "",
            },
          },
          {
            id: 5,
            groupName: "Группа 7-9 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "15:50 – 16:35",
              thursday: "",
              friday: "15:50 – 16:35",
              saturday: "",
            },
          },
          {
            id: 6,
            groupName: "Группа 5-6 лет",
            vacantPlaces: "Группа укомплектована, мест нет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "17:40 – 18:30",
              thursday: "",
              friday: "17:40 – 18:30",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/88875/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/35.jpg",
    },
    title: "Изостудия «Творец»",
    vacantPlaces: true,
    extraText: [5],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName: "Изостудия «Творец»",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Дубровская Наталия Вадимовна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Творческие занятия в студии – особый вид художественной деятельности, объединяющий в себе различные виды творчества: рисование, лепку, аппликацию, коллаж, витраж, конструирование.",
          "В программе: игровые занятия с изобразительными материалами; выполнение сюжетных композиций, сочетающие разные виды деятельности /рисование и конструирование, лепку и аппликацию, витраж и роспись. ",
          "Результат: в процессе творческих занятий дети смогут узнать о необычных приемах и способах в работе с изобразительными материалами /бумагой, пластиком, деревом, тканью, стеклом/. Творческие работы могут служить не только украшением интерьера, но и отличным подарком к праздникам.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 1",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "5 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "12:50 – 14:30",
              tuesday: "",
              wednesday: "",
              thursday: "12:50 – 14:30",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/99451/groups/",
      },
    ],
  },
  // Укомлектовано
  {
    image: {
      src: "img/Courses/Summer/17.jpg",
    },
    title: "Свет и цвет",
    vacantPlaces: false,
    extraText: [5, 6],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName: "Свет и цвет",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Сабирова Динара Рафаиловна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Программа «Свет и Цвет» предназначена для детей в возрасте 5-6 лет и включает в себя творческие занятия и различные опыты которые познакомят детей с основами света и цвета",
        ],
        groups: [
          {
            id: 0,
            vacantPlaces: "Группа укомплектована, мест нет",
            groupName: "Группа 1",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "17:00 – 18:10",
              thursday: "",
              friday: "17:00 – 18:10",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/99445/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/34.jpg",
    },
    title: "Чудеса из сундучка",
    vacantPlaces: true,
    extraText: [5, 6],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName: "Чудеса из сундучка",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Дубровская Наталия Вадимовна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Народная самодельная игрушка – это прекрасная возможность познакомить детей с традициями и обычаями прошлого, на основе которых поддерживается связь поколений. ",
          "В программе: занятия проходят в форме мастер-класса, где педагог одновременно показывает технику изготовления игрушки и сопровождает комментариями об истории, назначении и ее роли в повседневной жизни. Результат: дети узнают о приемах изготовления традиционных, народных игрушек. В процессе занятий дети научаться создавать куклы-обереги; куклы к праздникам; авторские игрушки по мотивам народных; украшения «в народном стиле».",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 1",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "5-6 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "15:00 – 16:40",
              tuesday: "",
              wednesday: "",
              thursday: "15:00 – 16:40",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/99453/groups/",
      },
    ],
  },
  // Укомлектовано
  {
    image: {
      src: "img/Courses/36.jpg",
    },
    title: "Живопись",
    vacantPlaces: false,
    extraText: [7, 8],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName: "Живопись",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Дубровская Наталия Вадимовна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Живопись – вид изобразительного искусства для передачи эмоционального состояния красками.  Основное средство изображения – цвет. ",
          "В программе: создание живописных композиций красками: акварель, гуашь, а также с использованием нетрадиционных материалов пластилин, шерсть, тушь. ",
          "Результат: в процессе творческих занятий дети освоят основные техники в работе с гуашью и акварелью, научатся воплощать на бумаге свои идеи и фантазии. С помощью художественных приемов дети откроют секреты в жанре пейзажа, портрета и натюрморта.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 1",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "12:50 – 14:30",
              thursday: "",
              friday: "12:50 – 14:30",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/99452/groups/",
      },
    ],
  },
  // Укомлектовано
  {
    image: {
      src: "img/Courses/16.jpg",
    },
    title: "Лепка",
    vacantPlaces: false,
    extraText: [7, 8],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName: "Лепка",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Сабирова Динара Рафаиловна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Программа  «Лепка» для детей 7-8. Будем лепить из разных пластичных материалов: воздушный пластилин, папье-маше, соленое тесто и т.д..",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 1",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "12:50 – 14:20",
              thursday: "",
              friday: "12:50 – 14:20",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/99447/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/12.jpg",
    },
    title: "Золотой наперсток",
    vacantPlaces: true,
    extraText: [7, 8, 9, 10, 11, 12],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName: "Золотой наперсток",
        teacher: {
          teacherPic: ["./img/About/23.png"],
          teacherName: ["Степаненко Лилия Викторовна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Данная программа поможет обучающимся научиться работать с выкройками и разрабатывать свои собственные эскизы, освоить швейное дело, ковровую вышивку. По итогу обучающиеся изготовят свою собственную линию одежды.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 7-8 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "12:50 – 14:20",
              tuesday: "",
              wednesday: "",
              thursday: "12:50 – 14:20",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа 7-8 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "12:50 – 14:20",
              wednesday: "",
              thursday: "16:40 – 18:25",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа 9-12 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "9-12 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "14:50 – 16:30",
              tuesday: "",
              wednesday: "",
              thursday: "14:50 – 16:30",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/88866/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/6.jpg",
    },
    title: "Английский клуб",
    vacantPlaces: true,
    extraText: [7, 8, 9, 10, 11, 12],
    // extraMonth: "старт в июле",
    category: "Социально-гуманитарная",
    programms: [
      {
        programmName: "Английский клуб",
        teacher: {
          teacherPic: ["./img/About/20.png"],
          teacherName: ["Ревенкова Екатерина Владимировна"],
        },
        category: "социально-гуманитарная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Обучение по программе способствует овладению навыками продуктивной и рецептивной речевой деятельности: аудирования, говорения, чтения, письма. Учащиеся приобретают навыки, предусмотренные соответствующим уровнем, формируют коммуникативные умения в четырех видах речевой деятельности.",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 7-8 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "10:00 – 10:45",
              tuesday: "",
              wednesday: "10:00 – 10:45",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 1,
            groupName: "Группа 7-8 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "7-8 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "10:00 – 10:45",
              wednesday: "",
              thursday: "10:00 – 10:45",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 2,
            groupName: "Группа 9-10 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "9-10 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "12:50 – 14:30",
              tuesday: "",
              wednesday: "12:50 – 14:30",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 3,
            groupName: "Группа 9-10 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "9-10 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "12:50 – 14:30",
              wednesday: "",
              thursday: "12:50 – 14:30",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 4,
            groupName: "Группа 11-12 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "11-12 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "14:40 – 15:25",
              tuesday: "",
              wednesday: "14:40 – 15:25",
              thursday: "",
              friday: "",
              saturday: "",
            },
          },
          {
            id: 5,
            groupName: "Группа 11-12 лет",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "11-12 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "",
              tuesday: "14:40 – 16:20",
              wednesday: "",
              thursday: "15:00 – 16:40",
              friday: "",
              saturday: "",
            },
          },
          // {
          //   id: 6,
          //   groupName: "Группа 13-14 лет",
          //   startDate: "01.06.2025",
          //   year: "1-й год обучения",
          //   age: "13-14 лет",
          //   signInButtonAllowed: true,
          //   schedule: {
          //     monday: "",
          //     tuesday: "",
          //     wednesday: "",
          //     thursday: "16:50 – 18:30",
          //     friday: "",
          //     saturday: "",
          //   },
          // },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/89410/groups/",
      },
    ],
  },
  // Укомлектовано
  {
    image: {
      src: "img/Courses/Summer/16.jpg",
    },
    title: "От росписи к принту",
    vacantPlaces: false,
    extraText: [9, 10, 11, 12],
    // extraMonth: "старт в июле",
    category: "Художественная",
    programms: [
      {
        programmName: "От росписи к принту",
        teacher: {
          teacherPic: ["./img/About/women-avatar.png"],
          teacherName: ["Сабирова Динара Рафаиловна"],
        },
        category: "художественная",
        duration: "18 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "Программа «От росписи к принту» где каждый ребенок не только познакомится с традиционном искусством (Мезенская, Городецкая роспись и тд.), но и сможет создать уникальный узор, отражающий его личное видение в технике линогравюры, с последующей печатью на футболке или шоппере",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 1",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "9-12 лет",
            signInButtonAllowed: false,
            schedule: {
              monday: "",
              tuesday: "",
              wednesday: "14:40 – 16:20",
              thursday: "",
              friday: "14:40 – 16:20",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/99446/groups/",
      },
    ],
  },
  {
    image: {
      src: "img/Courses/Summer/18.jpg",
    },
    title: "Азбука выживания",
    vacantPlaces: true,
    extraText: [13, 14, 15, 16, 17],
    // extraMonth: "старт в июле",
    category: "Физкультурно-спортивная",
    programms: [
      {
        programmName: "Азбука выживания",
        teacher: {
          teacherPic: ["./img/About/men-avatar.png"],
          teacherName: ["Михаевич Вадим Константинович"],
        },
        category: "физкультурно-спортивная",
        duration: "28 часов",
        price: "на бюджетной основе (бесплатно)",
        description: [
          "По программе могут заниматься дети и подростки 14 - 17 лет, проявляющие интерес в области начальной военной подготовки и не имеющие ограничений по здоровью в данной области",
        ],
        groups: [
          {
            id: 0,
            groupName: "Группа 1",
            startDate: "01.06.2025",
            year: "1-й год обучения",
            age: "13-17 лет",
            signInButtonAllowed: true,
            schedule: {
              monday: "17:00 – 18:40",
              tuesday: "",
              wednesday: "",
              thursday: "17:00 – 18:40",
              friday: "",
              saturday: "",
            },
          },
        ],
        signInButton: "https://dopobr.petersburgedu.ru/programs/99449/groups/",
      },
    ],
  },
];

export default coursesCardsData;
